import { PrismaClient, MallStatus, StoreStatus } from '@prisma/client';

const prisma = new PrismaClient();

const malls = [
  // Existing Malls
  {
    id: 'mall-1',
    name: 'Grand City Mall',
    description: 'A premier shopping destination featuring over 200 retail stores, luxury boutiques, and world-class dining options. The mall boasts stunning architecture with a glass atrium and spacious walkways.',
    address: '123 Central Avenue, Downtown District',
    area: 'Downtown',
    latitude: 40.7580,
    longitude: -73.9855,
    imageUrl: '/malls/grand-city-mall.png',
    status: MallStatus.EXISTING,
    openingHours: 'Mon-Sun: 10:00 AM - 10:00 PM',
    features: 'Luxury Brands,Food Court,Cinema Complex,Kids Play Area',
    storesCount: 220,
    amenities: 'Valet Parking,Free WiFi,ATM,Baby Care Rooms,Wheelchair Access',
  },
  {
    id: 'mall-2',
    name: 'Metro Plaza',
    description: 'Metro Plaza offers a modern shopping experience with a perfect blend of fashion, electronics, and lifestyle stores. Features an indoor amusement park and rooftop garden.',
    address: '456 Metro Boulevard, Midtown',
    area: 'Midtown',
    latitude: 40.7614,
    longitude: -73.9776,
    imageUrl: '/malls/metro-plaza.png',
    status: MallStatus.EXISTING,
    openingHours: 'Mon-Thu: 10:00 AM - 9:00 PM, Fri-Sun: 10:00 AM - 11:00 PM',
    features: 'Indoor Amusement Park,Rooftop Garden,Tech Hub,Art Gallery',
    storesCount: 180,
    amenities: 'Multi-level Parking,Restaurant Terrace,Concierge Service,Gift Wrapping',
  },
  {
    id: 'mall-3',
    name: 'Harbor Shopping Center',
    description: 'Experience waterfront shopping at its finest. Harbor Shopping Center combines retail therapy with scenic harbor views, featuring boutique stores and waterfront dining.',
    address: '789 Waterfront Road, Harbor District',
    area: 'Harbor District',
    latitude: 40.6892,
    longitude: -74.0445,
    imageUrl: '/malls/harbor-shopping.png',
    status: MallStatus.EXISTING,
    openingHours: 'Mon-Sun: 9:00 AM - 9:00 PM',
    features: 'Waterfront Views,Seafood Restaurants,Boutique Stores,Boat Tours',
    storesCount: 95,
    amenities: 'Boat Docking,Outdoor Seating,Seafood Market,Photo Spots',
  },
  {
    id: 'mall-4',
    name: 'Riverside Mall',
    description: 'Riverside Mall is a family-friendly shopping destination with a focus on affordable fashion and entertainment. Home to the largest indoor ice rink in the city.',
    address: '321 River Walk, East Side',
    area: 'East Side',
    latitude: 40.7484,
    longitude: -73.9857,
    imageUrl: '/malls/riverside-mall.png',
    status: MallStatus.EXISTING,
    openingHours: 'Mon-Sat: 10:00 AM - 10:00 PM, Sun: 11:00 AM - 8:00 PM',
    features: 'Ice Skating Rink,Family Entertainment,Outlet Stores,Event Hall',
    storesCount: 150,
    amenities: 'Ice Skate Rental,Party Rooms,Lost & Found,First Aid Station',
  },
  // Upcoming Malls
  {
    id: 'mall-5',
    name: 'Sky Tower Mall',
    description: "Set to become the city's tallest shopping complex, Sky Tower Mall will feature innovative vertical retail spaces, sky bridges connecting towers, and an observation deck.",
    address: '555 Cloud Street, Financial District',
    area: 'Financial District',
    latitude: 40.7074,
    longitude: -74.0113,
    imageUrl: '/malls/sky-tower.png',
    status: MallStatus.UPCOMING,
    expectedOpeningDate: 'June 2025',
    features: 'Vertical Shopping,Sky Bridges,Observation Deck,Helipad Access',
    storesCount: 300,
    amenities: 'Express Elevators,Sky Lounge,Private Suites,Rooftop Helipad',
  },
  {
    id: 'mall-6',
    name: 'Eco Garden Mall',
    description: 'A revolutionary eco-friendly mall concept featuring indoor gardens, sustainable architecture, and green technology. Will be the first carbon-neutral shopping center in the region.',
    address: '777 Green Valley Road, Nature District',
    area: 'Nature District',
    latitude: 40.7829,
    longitude: -73.9654,
    imageUrl: '/malls/eco-garden.png',
    status: MallStatus.UPCOMING,
    expectedOpeningDate: 'September 2025',
    features: 'Indoor Gardens,Solar Powered,Green Roof,Eco Stores',
    storesCount: 120,
    amenities: 'Electric Vehicle Charging,Bicycle Parking,Organic Food Court,Nature Trail',
  },
  {
    id: 'mall-7',
    name: 'Tech Hub Mall',
    description: 'The future of tech shopping arrives with Tech Hub Mall. Featuring VR experience zones, robot-assisted services, and the latest in consumer technology.',
    address: '888 Innovation Drive, Tech Valley',
    area: 'Tech Valley',
    latitude: 40.7549,
    longitude: -73.9840,
    imageUrl: '/malls/tech-hub.png',
    status: MallStatus.UPCOMING,
    expectedOpeningDate: 'March 2025',
    features: 'VR Experience Zones,Robot Services,Tech Showrooms,Innovation Lab',
    storesCount: 80,
    amenities: 'Smart Parking,AR Navigation,Tech Support Hub,Drone Delivery',
  },
  {
    id: 'mall-8',
    name: 'Lifestyle Village',
    description: 'A community-centered lifestyle destination combining shopping, dining, and wellness. Will feature an open-air design with pedestrian-friendly walkways and community spaces.',
    address: '999 Community Lane, Suburban West',
    area: 'Suburban West',
    latitude: 40.7282,
    longitude: -73.7949,
    imageUrl: '/malls/lifestyle-village.png',
    status: MallStatus.UPCOMING,
    expectedOpeningDate: 'December 2025',
    features: 'Open-Air Design,Wellness Center,Community Space,Farmers Market',
    storesCount: 140,
    amenities: 'Pet-Friendly Zones,Outdoor Yoga,Community Events,Sustainable Practices',
  },
];

const stores = [
  // Stores for Grand City Mall (mall-1)
  {
    id: 'store-1-1',
    mallId: 'mall-1',
    name: 'Zara',
    description: 'Spanish fashion retailer offering trendy clothing, shoes, and accessories for men, women, and children.',
    category: 'Fashion & Apparel',
    floor: 'Ground Floor',
    unitNumber: 'G-12',
    phone: '+1 212-555-0101',
    website: 'https://www.zara.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 10:00 AM - 9:30 PM',
  },
  {
    id: 'store-1-2',
    mallId: 'mall-1',
    name: 'Apple Store',
    description: 'Premium technology showcase featuring the latest Apple products, accessories, and expert support.',
    category: 'Electronics & Technology',
    floor: '1st Floor',
    unitNumber: '1-05',
    phone: '+1 212-555-0102',
    website: 'https://www.apple.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 10:00 AM - 9:00 PM',
  },
  {
    id: 'store-1-3',
    mallId: 'mall-1',
    name: 'Starbucks',
    description: 'World-famous coffee house serving premium coffee, espresso drinks, and delicious snacks.',
    category: 'Food & Dining',
    floor: 'Ground Floor',
    unitNumber: 'G-08',
    phone: '+1 212-555-0103',
    website: 'https://www.starbucks.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 8:00 AM - 10:00 PM',
  },
  {
    id: 'store-1-4',
    mallId: 'mall-1',
    name: 'H&M',
    description: 'Global fashion brand offering stylish and affordable clothing for all ages.',
    category: 'Fashion & Apparel',
    floor: 'Ground Floor',
    unitNumber: 'G-15',
    phone: '+1 212-555-0104',
    website: 'https://www.hm.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 10:00 AM - 9:30 PM',
  },
  {
    id: 'store-1-5',
    mallId: 'mall-1',
    name: 'Sephora',
    description: 'Beauty retailer featuring thousands of products from top brands including makeup, skincare, and fragrance.',
    category: 'Health & Beauty',
    floor: '1st Floor',
    unitNumber: '1-12',
    phone: '+1 212-555-0105',
    website: 'https://www.sephora.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 10:00 AM - 9:00 PM',
  },

  // Stores for Metro Plaza (mall-2)
  {
    id: 'store-2-1',
    mallId: 'mall-2',
    name: 'Samsung Experience',
    description: 'Interactive showroom featuring the latest Samsung smartphones, TVs, appliances, and smart home solutions.',
    category: 'Electronics & Technology',
    floor: '1st Floor',
    unitNumber: '1-01',
    phone: '+1 212-555-0201',
    website: 'https://www.samsung.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 10:00 AM - 9:00 PM',
  },
  {
    id: 'store-2-2',
    mallId: 'mall-2',
    name: 'Nike',
    description: 'Athletic footwear, apparel, and equipment for all sports and fitness activities.',
    category: 'Sports & Outdoors',
    floor: 'Ground Floor',
    unitNumber: 'G-20',
    phone: '+1 212-555-0202',
    website: 'https://www.nike.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 10:00 AM - 9:30 PM',
  },
  {
    id: 'store-2-3',
    mallId: 'mall-2',
    name: 'The Cheesecake Factory',
    description: 'Popular casual dining restaurant famous for extensive menu and legendary cheesecakes.',
    category: 'Food & Dining',
    floor: '2nd Floor',
    unitNumber: '2-10',
    phone: '+1 212-555-0203',
    website: 'https://www.thecheesecakefactory.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Thu: 11:00 AM - 11:00 PM, Fri-Sat: 11:00 AM - 12:00 AM, Sun: 11:00 AM - 10:00 PM',
  },
  {
    id: 'store-2-4',
    mallId: 'mall-2',
    name: 'Uniqlo',
    description: 'Japanese casual wear designer offering high-quality, affordable clothing for all.',
    category: 'Fashion & Apparel',
    floor: 'Ground Floor',
    unitNumber: 'G-05',
    phone: '+1 212-555-0204',
    website: 'https://www.uniqlo.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 10:00 AM - 9:30 PM',
  },

  // Stores for Harbor Shopping Center (mall-3)
  {
    id: 'store-3-1',
    mallId: 'mall-3',
    name: 'Gucci',
    description: 'Luxury Italian fashion house offering high-end clothing, handbags, shoes, and accessories.',
    category: 'Fashion & Apparel',
    floor: 'Ground Floor',
    unitNumber: 'G-01',
    phone: '+1 212-555-0301',
    website: 'https://www.gucci.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 10:00 AM - 8:00 PM',
  },
  {
    id: 'store-3-2',
    mallId: 'mall-3',
    name: 'Tiffany & Co.',
    description: 'Iconic luxury jewelry brand known for exceptional diamonds and timeless designs.',
    category: 'Jewelry & Accessories',
    floor: 'Ground Floor',
    unitNumber: 'G-02',
    phone: '+1 212-555-0302',
    website: 'https://www.tiffany.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 10:00 AM - 7:00 PM',
  },
  {
    id: 'store-3-3',
    mallId: 'mall-3',
    name: 'The Seafood Grill',
    description: 'Upscale waterfront restaurant specializing in fresh seafood and stunning harbor views.',
    category: 'Food & Dining',
    floor: '1st Floor',
    unitNumber: '1-15',
    phone: '+1 212-555-0303',
    website: 'https://www.theseafoodgrill.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 11:00 AM - 10:00 PM',
  },

  // Stores for Riverside Mall (mall-4)
  {
    id: 'store-4-1',
    mallId: 'mall-4',
    name: 'Target',
    description: 'Popular retail chain offering a wide variety of products including clothing, electronics, and home goods.',
    category: 'Home & Lifestyle',
    floor: 'Ground Floor',
    unitNumber: 'G-30',
    phone: '+1 212-555-0401',
    website: 'https://www.target.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 8:00 AM - 10:00 PM',
  },
  {
    id: 'store-4-2',
    mallId: 'mall-4',
    name: 'Barnes & Noble',
    description: 'Major bookseller offering a vast selection of books, magazines, and educational materials.',
    category: 'Books & Stationery',
    floor: '1st Floor',
    unitNumber: '1-20',
    phone: '+1 212-555-0402',
    website: 'https://www.barnesandnoble.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 10:00 AM - 9:00 PM',
  },
  {
    id: 'store-4-3',
    mallId: 'mall-4',
    name: 'Ice Skating Rink',
    description: 'The largest indoor ice skating rink in the city, offering public skating sessions and lessons.',
    category: 'Entertainment',
    floor: '2nd Floor',
    unitNumber: '2-01',
    phone: '+1 212-555-0403',
    website: 'https://www.riversideicerink.com',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 9:00 AM - 10:00 PM',
  },
  {
    id: 'store-4-4',
    mallId: 'mall-4',
    name: 'Food Court',
    description: 'Diverse food court featuring cuisines from around the world with seating for 500+ guests.',
    category: 'Food & Dining',
    floor: '3rd Floor',
    unitNumber: '3-01',
    phone: '+1 212-555-0404',
    status: StoreStatus.OPEN,
    openingHours: 'Mon-Sun: 10:00 AM - 9:30 PM',
  },

  // Stores for Sky Tower Mall (mall-5) - Upcoming
  {
    id: 'store-5-1',
    mallId: 'mall-5',
    name: 'Louis Vuitton',
    description: 'World-renowned luxury fashion house offering leather goods, handbags, and accessories.',
    category: 'Fashion & Apparel',
    floor: 'Ground Floor',
    unitNumber: 'G-01',
    status: StoreStatus.COMING_SOON,
  },
  {
    id: 'store-5-2',
    mallId: 'mall-5',
    name: 'Tesla Showroom',
    description: 'Electric vehicle showroom featuring the latest Tesla models and sustainable energy products.',
    category: 'Electronics & Technology',
    floor: '1st Floor',
    unitNumber: '1-10',
    status: StoreStatus.COMING_SOON,
  },
  {
    id: 'store-5-3',
    mallId: 'mall-5',
    name: 'Sky Lounge Restaurant',
    description: 'Premium fine dining experience with panoramic city views from the 50th floor.',
    category: 'Food & Dining',
    floor: '50th Floor',
    unitNumber: '50-01',
    status: StoreStatus.COMING_SOON,
  },

  // Stores for Eco Garden Mall (mall-6) - Upcoming
  {
    id: 'store-6-1',
    mallId: 'mall-6',
    name: 'Whole Foods Market',
    description: 'Organic and natural foods supermarket with focus on sustainable and locally sourced products.',
    category: 'Food & Dining',
    floor: 'Ground Floor',
    unitNumber: 'G-05',
    status: StoreStatus.COMING_SOON,
  },
  {
    id: 'store-6-2',
    mallId: 'mall-6',
    name: 'Lululemon',
    description: 'Athletic apparel retailer specializing in yoga-inspired clothing and accessories.',
    category: 'Sports & Outdoors',
    floor: '1st Floor',
    unitNumber: '1-08',
    status: StoreStatus.COMING_SOON,
  },
  {
    id: 'store-6-3',
    mallId: 'mall-6',
    name: 'Garden Spa & Wellness',
    description: 'Eco-friendly spa offering organic treatments, yoga classes, and wellness programs.',
    category: 'Health & Beauty',
    floor: '2nd Floor',
    unitNumber: '2-15',
    status: StoreStatus.COMING_SOON,
  },

  // Stores for Tech Hub Mall (mall-7) - Upcoming
  {
    id: 'store-7-1',
    mallId: 'mall-7',
    name: 'Microsoft Store',
    description: 'Technology showcase featuring Surface devices, Xbox, Windows PCs, and productivity software.',
    category: 'Electronics & Technology',
    floor: 'Ground Floor',
    unitNumber: 'G-01',
    status: StoreStatus.COMING_SOON,
  },
  {
    id: 'store-7-2',
    mallId: 'mall-7',
    name: 'Sony Center',
    description: 'Experience center for Sony electronics, gaming, entertainment, and professional products.',
    category: 'Electronics & Technology',
    floor: 'Ground Floor',
    unitNumber: 'G-02',
    status: StoreStatus.COMING_SOON,
  },
  {
    id: 'store-7-3',
    mallId: 'mall-7',
    name: 'VR Arcade',
    description: 'State-of-the-art virtual reality gaming center with the latest VR experiences.',
    category: 'Entertainment',
    floor: '2nd Floor',
    unitNumber: '2-05',
    status: StoreStatus.COMING_SOON,
  },

  // Stores for Lifestyle Village (mall-8) - Upcoming
  {
    id: 'store-8-1',
    mallId: 'mall-8',
    name: 'Williams-Sonoma',
    description: 'Premium home furnishings and kitchenware store with expert culinary demonstrations.',
    category: 'Home & Lifestyle',
    floor: 'Ground Floor',
    unitNumber: 'G-10',
    status: StoreStatus.COMING_SOON,
  },
  {
    id: 'store-8-2',
    mallId: 'mall-8',
    name: 'Pottery Barn',
    description: 'Home furnishing store offering stylish and comfortable furniture and decor.',
    category: 'Home & Lifestyle',
    floor: 'Ground Floor',
    unitNumber: 'G-11',
    status: StoreStatus.COMING_SOON,
  },
  {
    id: 'store-8-3',
    mallId: 'mall-8',
    name: 'Outdoor Farmers Market',
    description: 'Open-air market featuring local farmers, artisans, and sustainable food vendors.',
    category: 'Food & Dining',
    floor: 'Ground Floor',
    unitNumber: 'Outdoor',
    status: StoreStatus.COMING_SOON,
  },
  {
    id: 'store-8-4',
    mallId: 'mall-8',
    name: 'Yoga Studio',
    description: 'Wellness studio offering yoga, meditation, and fitness classes in a serene environment.',
    category: 'Health & Beauty',
    floor: '1st Floor',
    unitNumber: '1-20',
    status: StoreStatus.COMING_SOON,
  },
];

async function main() {
  console.log('Starting seed...');

  // Clear existing stores and malls
  await prisma.store.deleteMany({});
  console.log('Cleared existing stores');
  
  await prisma.mall.deleteMany({});
  console.log('Cleared existing malls');

  // Insert new malls
  for (const mall of malls) {
    await prisma.mall.create({
      data: mall,
    });
    console.log(`Created mall: ${mall.name}`);
  }

  // Insert stores
  for (const store of stores) {
    await prisma.store.create({
      data: store,
    });
    console.log(`Created store: ${store.name}`);
  }

  console.log('Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('Error during seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
